title: hackEDU Shipped Projects
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://shipped.hackedu.us" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
